import type { Metadata } from 'next';
import './globals.css';
import ReactQueryProvider from '@/lib/ReactQueryProvider';
import PushNotificationListener from '@/components/PushNotificationListener';

export const metadata: Metadata = {
  title: 'silver bridge',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <ReactQueryProvider>
          {children}
          <PushNotificationListener />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
